---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: "storage.${SECRET_PRIVATE_DOMAIN}"
  share: /storage/backups # showmount -e ${SECRET_PRIVATE_DOMAINs}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
