# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:E4q8hqFl0i7J,iv:zhc0/RxIr79/LIqUAfcXiy16/NgLM/6vLWfqOnowUks=,tag:ou1Y/beZt0PL7Qdb7vpMnw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Enwz2wBvoBBGuMr5QxOPH9LCGOClIbM=,iv:nL0twacLOs46xcNU68wlUd3Kr/Tff2ry7lZGRWSQRY4=,tag:JKfsdV8TlssSX6RuNwL+dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU1hxanZIeEtNL055SnNO
            L0ZIbVlJSXZwVmE3eXdKSnAxcDJ2R3YzRVZZClh2N1JaMU1hU3lXT2JQMWtpL3Nu
            NWhISk8xM0ozam1qUmZMUTNsSkw0NVEKLS0tIElGOUJ2K25GTTlySDV0TWxOZk4z
            U0VSbnk0VE1RYWNra0ZkdWdneHB3SVUKD5B1+YbiFdorl8fBN5+wKr1j2yhnIiNU
            2crOiwbimjy+BkitLItox3jljOMCB7k3iZfD3w+hh31Tbvxupy+gjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-27T16:06:08Z"
    mac: ENC[AES256_GCM,data:sX4xx/40Zggc7D0Esr3eoBfOeJXY2RU9B2csS0BCzr/0sLkkwp/NSRu8ERZQZdUQ0D/EzL/puYrzblXNC9DwjALKDnGtiteTK5iDNqxdtLx2T1ZYZ/HdPUR9Lr00fGRf/IKPBi4+2boeZpIR+Mi2hm0F4S83Z+zwOWxY6UiTURQ=,iv:2nDpAdnyzRjv4UeYyTVQHACyT/0NWLEYcK+n9Xm6rXw=,tag:7J/zVBUt7GzH8jr4X4JQEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
