---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/Amsterdam
  METALLB_LB_RANGE: 10.20.0.230-10.20.0.240
  METALLB_K8S_GATEWAY_ADDR: 10.20.0.230
  METALLB_INGRESS_ADDR: 10.20.0.231
